Add: macos aarch64 release
Gobidev/pfetch-rs pull request #13
Opened 2023-03-07 19:37 UTC by 21st-centuryman

I wanted to add this package to homebrew so this would be the first step in achieving this.

Love the package btw. cheers

2023-03-07 20:17 UTC, 21st-centuryman commented
Also if there is anything I can add/contribute to with this just hmu.

2023-03-08 07:40 UTC, Gobidev requested changes
Thank you for offering your help^^
Currently these are the things I have planned for this project:
- add Windows binary to release workflow that is not .tar.gz compressed

- make the following changes in `libmacchina`:
   - add Wayland WM detection
   - find fast method to count `nix` packages
   - count Windows `winget` and `chocolatey` packages

Aside from that, the project is more or less done, as it is supposed to be minimalistic. So unless someone has an awesome idea, there aren't really any big features to work on.

2023-03-08 07:40 UTC, Gobidev commented on .github/workflows/release.yml
> +            cross: true
`cross` is not needed for the x86 build, as the job runs on macos x86_64

2023-03-08 07:46 UTC, merged

2023-03-08 17:44 UTC, Gobidev commented
I added a macos aarch64 binary to the latest release manually, so you should be able to add it to homebrew if you want :)

2023-03-09 17:08 UTC, 21st-centuryman commented
Awesome. I will set this up when I find the time. 

Thanks for your help!

2023-03-09 19:55 UTC, 21st-centuryman commented
PR created:
https://github.com/Homebrew/homebrew-core/pull/125251

Bear in mind it is my first homebrew formula PR so I might have overlooked something.

2023-03-09 20:28 UTC, Gobidev commented
All right, thank you!