docs: update the license
Gobidev/pfetch-rs pull request #53
Opened 2024-06-21 21:31 UTC by somerand0mcat

2024-06-24 08:48 UTC, Gobidev requested changes

2024-06-24 08:48 UTC, Gobidev commented on LICENSE
> +Copyright (c) 2024 Adrian Groh
I think I would like a span like `2023-2024` more.

2024-06-25 18:29 UTC, somerand0mcat commented on LICENSE
> +Copyright (c) 2024 Adrian Groh
alright

2024-06-25 18:30 UTC, somerand0mcat commented on LICENSE
> +Copyright (c) 2024 Adrian Groh
its fixed

2024-06-25 19:11 UTC, Gobidev approved these changes

2024-06-25 19:13 UTC, merged